#!/bin/bash

# build / deploy flags
build_containers=false
deploy_containers=false
clean_deploy=false

# core paths of fedn library and configurations
FEDN_PATH=modules/fedn
CONF_PATH=config/fedn_config

# secondary paths to hold container data
minio_data_path=~/fedn_data/minio_data
mongo_data_path=~/fedn_data/mongo_data
mexpr_data_path=~/fedn_data/mexpr_data
tm_overlay_path=~/fedn_data/overalys

# check requested user options
print_usage() {
    echo " "
    echo "Usage:"
    echo "  prepare_fedn [options]"
    echo ""
    echo "Options:"
    echo "  -h      show brief help"
    echo "  -b      build fedn containers"
    echo "  -d      deploy fedn network"
    echo "  -c      clean deployment"
    echo ""
}

while getopts 'bdhc' flag; do
    case "${flag}" in
        b) build_containers=true ;;
        d) deploy_containers=true ;;
        c) clean_deploy=true ;;
        h) print_usage
            exit 0 ;;
        *) print_usage
            exit 1 ;;
    esac
done

# build containers if requested
if [ "$build_containers" = true ]; then
    # prepare build directory
    if test -d build; then
        rm -rf build
    fi
    mkdir build && mkdir build/containers

    # build containers
    apptainer build build/containers/fedn_minio.sif containers/fedn_minio.def
    apptainer build build/containers/fedn_mongo.sif containers/fedn_mongo.def
    apptainer build build/containers/fedn_mongo-express.sif containers/fedn_mongo-express.def
    apptainer build --build-arg FEDN_PATH=$FEDN_PATH --build-arg CONF_PATH=$CONF_PATH build/containers/fedn.sif containers/fedn.def
fi

# deploy containers if requested
if [ "$deploy_containers" = true ]; then
    # clean up if fresh deployment requested
    if [ "$clean_deploy" = true ]; then
        rm -rf "$minio_data_path" "$mongo_data_path" "$mexpr_data_path" "$tm_overlay_path"
        mkdir -p "$minio_data_path" "$mongo_data_path" "$mongo_data_path/db" "$mexpr_data_path" "$tm_overlay_path"
    fi

    # deploy common fedn services like mongodb, minio etc.
    apptainer instance start --bind $minio_data_path:/data build/containers/fedn_minio.sif minio
    apptainer instance start --bind $mongo_data_path:/data build/containers/fedn_mongo.sif mongo
    apptainer instance start --bind $mexpr_data_path:/data build/containers/fedn_mongo-express.sif mongo-express
    
    # deploy a reducer to act as dashboard
    apptainer overlay create --sparse --size 1024 $tm_overlay_path/dashboard_overlay.img
    apptainer instance start  --overlay $tm_overlay_path/dashboard_overlay.img build/containers/fedn.sif dashboard
    apptainer exec --pwd /app --overlay $tm_overlay_path/dashboard_overlay.img instance://dashboard fedn run dashboard -n reducer --init=/app/config/settings-reducer.yaml &
    
    # deploy the api server
    apptainer overlay create --sparse --size 1024 $tm_overlay_path/api_overlay.img
    apptainer instance start  --overlay $tm_overlay_path/api_overlay.img build/containers/fedn.sif api-server
    apptainer exec --pwd /app --overlay $tm_overlay_path/api_overlay.img instance://api-server python fedn/fedn/network/api/server.py &
    
    # deploy a combiner for model aggregations
    apptainer overlay create --sparse --size 1024 $tm_overlay_path/combiner_overlay.img
    apptainer instance start  --overlay $tm_overlay_path/combiner_overlay.img build/containers/fedn.sif combiner
    apptainer exec --pwd /app --overlay $tm_overlay_path/combiner_overlay.img instance://combiner fedn run combiner --init=/app/config/settings-combiner.yaml &

    # deploy some clients
    apptainer overlay create --sparse --size 1024 $tm_overlay_path/client_overlay.img
    apptainer instance start  --overlay $tm_overlay_path/client_overlay.img build/containers/fedn.sif client
    apptainer exec --pwd /app --overlay $tm_overlay_path/client_overlay.img instance://client fedn run client --init=/app/config/settings-client.yaml &
fi
