#!/bin/bash

build_containers=false
deploy_containers=false
clean_deploy=false
minio_data_path=~/fedn_data/minio_data
mongo_data_path=~/fedn_data/mongo_data
mexpr_data_path=~/fedn_data/mexpr_data

print_usage() {
    echo " "
    echo "Usage:"
    echo "  prepare_fedn [options]"
    echo ""
    echo "Options:"
    echo "  -h      show brief help"
    echo "  -b      build fedn containers"
    echo "  -d      deploy fedn network"
    echo "  -c      clean deployment"
    echo ""
}

while getopts 'bdhc' flag; do
    case "${flag}" in
        b) build_containers=true ;;
        d) deploy_containers=true ;;
        c) clean_deploy=true ;;
        h) print_usage
            exit 0 ;;
        *) print_usage
            exit 1 ;;
    esac
done

# build containers if requested
if [ "$build_containers" = true ]; then
    # prepare build directory
    if test -d build; then
        rm -rf build
    fi
    mkdir build && mkdir build/containers

    # build containers
    apptainer build build/containers/fedn_minio.sif containers/fedn_minio.def
    apptainer build build/containers/fedn_mongo.sif containers/fedn_mongo.def
    apptainer build build/containers/fedn_mongo-express.sif containers/fedn_mongo-express.def
    apptainer build --build-arg FEDN_PATH=modules/fedn --build-arg CONF_PATH=config/fedn_config build/containers/fedn.sif containers/fedn.def
fi

# deploy containers if requested
if [ "$deploy_containers" = true ]; then
    if [ "$clean_deploy" = true ]; then
        rm -rf "$minio_data_path" "$mongo_data_path" "$mexpr_data_path"
        mkdir  "$minio_data_path" "$mongo_data_path" "$mexpr_data_path"
    fi

    # deploy common fedn services like mongodb, minio etc.
    apptainer instance start --bind $minio_data_path:/data build/containers/fedn_minio.sif minio
    apptainer instance start --bind $mongo_data_path:/data build/containers/fedn_mongo.sif mongo
    apptainer instance start --bind $mexpr_data_path:/data build/containers/fedn_mongo-express.sif mongo-express
    
    # deploy a reducer to act as dashboard
    apptainer instance start build/containers/fedn.sif dashboard
    apptainer exec --pwd /app instance://dashboard fedn run dashboard -n reducer --init=/app/config/settings-reducer.yaml &
    
    # deploy a combiner for model aggregations
    apptainer instance start build/containers/fedn.sif combiner
    apptainer exec --pwd /app instance://combiner fedn run combiner --init=/app/config/settings-combiner.yaml &
    
    # deploy the api server
    apptainer instance start build/containers/fedn.sif api-server
    apptainer exec --pwd /app instance://api-server python fedn/fedn/network/api/server.py &

    # deploy some clients
    # apptainer exec build/containers/fedn.sif fedn run client --init=/app/config/settings-client.yaml &
fi
