MODEL_CONFIGS:
  MODEL_NAME: LENET-1CH           # Options: [SIMPLE-MLP, SIMPLE-CNN]
  NUM_CLASSES: 10

CLIENT_CONFIGS:
  RUN_DEVICE: auto                # Options: [auto, cpu, cuda]
  LOCAL_EPCH: 1
  BATCH_SIZE: 64
  LEARN_RATE: 0.001
  OPTIMIZER: ADAM                 # Options: [ADAM, SGD]
  CRITERION: CROSSENTROPY         # Options: [CROSSENTROPY, NLLL]

DATASET_CONFIGS:
    DATASET_NAME: MNIST             # Options: [MNIST, EMNIST, CIFAR-10]
    DATASET_DOWN: True              # Options: [True, False]
    DATASET_PATH: ./temp/data
    N_DATA_SPLIT: 5
    DIRICHLET_ALPHA: 100.0
    RANDOM_SEED: 333